### ISSUE TITLE
Ambient light module doesn't work properly. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#763] opened 2021-06-19 09:42 UTC
Problem:

If the ambient light is used to allow definition of exposure times with no real light connected experiments fail as the experiment module doesn't properly pick up the exposure time and the camera exposures don't get set in the action table. 

Work around:
Use the SimpleLight module with no triggerLine or triggerSource definition and this does what we want.

**Comment by carandraug** [comment] 2021-06-19 17:29
Closing as duplicate of issue #738.

**Closed by carandraug** 2021-06-19 17:29 UTC
Labels: duplicate
