### ISSUE TITLE
Customize light frequencies option overlays in the wrong place

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#660] opened 2020-07-27 07:41 UTC
The customize light frequencies option in the multi-site experiment panel. overlays the new options on top of the window and over existing fields.

**Comment by carandraug** [comment] 2020-07-27 09:33
I can't replicate it under GTK3 (wxPython 4.1.0). What OS and wxPython are you running? Can you provide a screenshoot?

I have seen a similar issue on the single site experiment panel but intermittent, it seems to be dependent on the order one changes "Experiment type" but I haven't been abled to reproduce it reliably.

**Comment by juliomateoslangerak** [comment] 2020-07-27 09:59
I'm running on wx 4.1.0 (windows 10). Here you have the screenshots with and without the option
![image](https://user-images.githubusercontent.com/7799110/88529545-72092200-d000-11ea-98fd-264fe92d1d9f.png)
![image](https://user-images.githubusercontent.com/7799110/88529667-9b29b280-d000-11ea-92ce-c25f8ee6aa13.png)

**Comment by juliomateoslangerak** [comment] 2020-07-27 10:00
Still on python 3.6... Will check if that matters.

**Comment by carandraug** [comment] 2020-07-27 10:05
Ah! I now see the "Customize light frequencies" button (I didn't before and thought you meant the "expose all cameras simultaneously"). I can reproduce it on GTK3, wxPython 4.1.0, and Python 3.7.

**Comment by carandraug** [comment] 2020-07-27 11:25
This is now fixed with 60b88b3f39fdedc4fbaaaf2049c5d9fe6c20da21 . It was a matter of calling `Layout` after showing/hiding the light frequencies panel.

**Closed by carandraug** 2020-07-27 11:25 UTC
Labels: GUI
