### ISSUE TITLE
MacroStageXY dialog not working

### ISSUE THREAD

**Issue by dstoychev** [MicronOxford/cockpit#604] opened 2020-05-14 18:53 UTC
Right-clicking on a MacroStageXY should bring up a dialog window, but this does not work for me. I get the following error:

```
Traceback (most recent call last):
  File "C:\cockpit\cockpit\gui\macroStage\macroStageXY.py", line 540, in OnRightClick
    values=cockpit.gui.dialogs.getNumberDialog.getManyNumbersFromUser(
AttributeError: module 'cockpit.gui.dialogs' has no attribute 'getNumberDialog'
```

I can fix this by adding ``import cockpit.gui.dialogs.getNumberDialog`` to the list of imports.

**Comment by carandraug** [comment] 2020-05-17 14:34
The fix is simple, the issue is weird. It is weird because we had another missing import of `getNumberDialog` recently (issue #591). I have looked into the logs (`git log -S getNumberDialog`)  and seems the reason for all those issue was that the module used to be imported in `cockpit.handlers.lightSource` which was removed in 3631d511cde1.

I have pushed your fix in d3700967d237 where I also fixed two other missing imports of `getNumberDialog`. Closing as fixed.

**Closed by carandraug** 2020-05-17 14:34 UTC
