### ISSUE TITLE
Need checks on directory/file existence.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#439] opened 2019-01-17 13:27 UTC
If the data directory doesn't exist (eg drive not mounted in windows) then cockpit dies silently. There are errors on the console but this vanishes too quickly to be read. Need a dialog or something similar to say why it is dying

**Comment by carandraug** [comment] 2019-10-03 16:28
I took a look at this issue and the problem is not whether the directory for the data already exists. If the directory does not exist, then cockpit will create it, and that works fine. The problem is if the user does not have permissions to create the non-existing directory. In which case, it fails with:

```
Traceback (most recent call last):
  File "/home/carandraug/.local/bin/cockpit", line 11, in <module>
    load_entry_point('cockpit', 'gui_scripts', 'cockpit')()
  File "/home/carandraug/src/cockpit/cockpit/__init__.py", line 344, in main
    cockpit.util.files.initialize(config)
  File "/home/carandraug/src/cockpit/cockpit/util/files.py", line 73, in initialize
    _ensureDirectoriesExist()
  File "/home/carandraug/src/cockpit/cockpit/util/files.py", line 90, in _ensureDirectoriesExist
    os.makedirs(directory)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/non-existent'
```

**Comment by carandraug** [comment] 2019-10-03 16:56
I have a proposal for this fix on my try-catch-init-issue439 branch or https://github.com/carandraug/cockpit/commit/11b7f0191520a97784f2d78505ea6ec5f641533c

This is more than just catching a failure to create the directory, this will catch any exception during the initialisation before the CockpitApp being created.

**Comment by iandobbie** [comment] 2019-10-03 20:46
Yes exactly. Maria’s config has it on a network drive. If the drive can’t be mounted then this fails badly. But we should return a reasonable error message not just hang.

Ian

Sent from my iPhone

On 3 Oct 2019, at 17:29, Carnë Draug <notifications@github.com<mailto:notifications@github.com>> wrote:


I took a look at this issue and the problem is not whether the directory for the data already exists. If the directory does not exist, then cockpit will create it, and that works fine. The problem is if the user does not have permissions to create the non-existing directory. In which case, it fails with:

Traceback (most recent call last):
  File "/home/carandraug/.local/bin/cockpit", line 11, in <module>
    load_entry_point('cockpit', 'gui_scripts', 'cockpit')()
  File "/home/carandraug/src/cockpit/cockpit/__init__.py", line 344, in main
    cockpit.util.files.initialize(config)
  File "/home/carandraug/src/cockpit/cockpit/util/files.py", line 73, in initialize
    _ensureDirectoriesExist()
  File "/home/carandraug/src/cockpit/cockpit/util/files.py", line 90, in _ensureDirectoriesExist
    os.makedirs(directory)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/non-existent'

**Comment by carandraug** [comment] 2019-10-03 22:54
> If the drive can’t be mounted then this fails badly. But we should return a reasonable error message not just hang.

When I tried to replicate the issue (setting `data-dir` to a directory without enough permissions), cockpit just exited after failing to create the directory, it didn't hang. Maybe it's related to being a network drive on windows?

Anyway, the problem is that there's some initialisation that get's done before starting the wx App. And if it fails during those steps, there's no wx to show a GUI dialog. The above patch creates an different wx App just to show the error and exit.

**Comment by carandraug** [comment] 2021-02-11 16:31
I have rebased and pushed the change I proposed 17 months ago. Closing as fixed.

**Closed by carandraug** 2021-02-11 16:31 UTC
