### ISSUE TITLE
Tooltips in the python shell window and python 3.11

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#848] opened 2023-02-15 16:18 UTC
The python shell window in cockpit is using inspect module to get tooltips and provide arguments to functions to help users. The inspect module no longer has formatargspec causing errors and my cockpit to crash on windows 10 with python 3.11.1

**Comment by carandraug** [comment] 2023-02-15 16:23
Not our issue. Duplicate of wxWidgets/Phoenix#2213. Closing.

**Closed by carandraug** 2023-02-15 16:23 UTC
