### ISSUE TITLE
Master now broken on Mac wxpython issues. 

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#625] opened 2020-06-24 11:48 UTC
wxpython 4.1.0 on the mac has an assertion error
Traceback (most recent call last):
  File "/Users/ian/src/cockpit/cockpit/__init__.py", line 165, in OnInit
    module = importlib.import_module(module_name)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ian/src/cockpit/cockpit/gui/touchscreen.py", line 811, in <module>
    class LightToggleButton(SBitmapToggleButton):
  File "/Users/ian/src/cockpit/cockpit/gui/touchscreen.py", line 825, in LightToggleButton
    mask = wx.Mask(_bmp)
wx._core.wxAssertionError: C++ assertion "v == 0 || v == 3*0xFF" failed at /Users/robind/projects/bb2/dist-osx-py37/build/ext/wxWidgets/src/osx/core/bitmap.cpp(1563) in InitFromMonoBitmap(): Non-monochrome bitmap supplied

wxpython 4.0.7 has a sizer issue

Traceback (most recent call last):
  File "/Users/ian/src/cockpit/cockpit/__init__.py", line 168, in OnInit
    module.makeWindow(main_window)
  File "/Users/ian/src/cockpit/cockpit/gui/macroStage/macroStageWindow.py", line 327, in makeWindow
    window = MacroStageWindow(parent)
  File "/Users/ian/src/cockpit/cockpit/gui/macroStage/macroStageWindow.py", line 300, in __init__
    sizer.Add(buttons_sizer, wx.SizerFlags().CentreHorizontal())
AttributeError: 'SizerFlags' object has no attribute 'CentreHorizontal'

**Comment by carandraug** [comment] 2020-06-24 13:01
> wxpython 4.1.0 on the mac has an assertion error

Duplicate of #613 

> wxpython 4.0.7 has a sizer issue

Fixed with e2b835762cc1f67df (I forgot to put the issue number on the commit message).

**Closed by carandraug** 2020-06-24 13:01 UTC
