### ISSUE TITLE
microscope stage device parameter issue.

### ISSUE THREAD

**Issue by iandobbie** [MicronOxford/cockpit#634] opened 2020-07-07 16:57 UTC
The latest updates have caused an issue.

From devices/microscopeDevice.py
  `     self._handler = PositionerHandler(self.name, group_name,
                                          eligible_for_experiments, callbacks,
                                          self._index, step_sizes, step_index,
                                          hard_limits, soft_limits)`

But the handler/stagePositioner.py
`    def __init__(self, name, groupName, isEligibleForExperiments, callbacks, 
            axis, hardLimits, softLimits = None):`

So the handler doesn't have the step_size and step_index and on startup it generates the error....

Traceback (most recent call last):
  File "/Users/ian/src/cockpit/cockpit/__init__.py", line 139, in OnInit
    for i, device in enumerate(cockpit.depot.initialize(depot_config)):
  File "/Users/ian/src/cockpit/cockpit/depot.py", line 288, in initialize
    for device in deviceDepot.initialize(config):
  File "/Users/ian/src/cockpit/cockpit/depot.py", line 158, in initialize
    self.initDevice(d)
  File "/Users/ian/src/cockpit/cockpit/depot.py", line 226, in initDevice
    device.initialize()
  File "/Users/ian/src/cockpit/cockpit/devices/microscopeDevice.py", line 579, in initialize
    units_per_um, self.name))
  File "/Users/ian/src/cockpit/cockpit/devices/microscopeDevice.py", line 453, in __init__
    hard_limits, soft_limits)
TypeError: __init__() takes from 7 to 8 positional arguments but 10 were given

**Comment by carandraug** [comment] 2020-07-07 17:14
Removing step sizes from devices and handlers is by design. That was done on master. `PositionerHandler` is not used on `microscopeDevice.py` so I'm guessing you've merged master into your "pos-fix" branch or something like that. You will need to adjust the code. This is one of the reasons why #572 was blocked by the step size stuff on #612.

Closing as invalid.

**Closed** 2020-07-07 17:14 UTC
Labels: invalid
