### ISSUE TITLE
Using Gain button with Zyla cameras freezes cockpit

### ISSUE THREAD

**Issue by juliomateoslangerak** [MicronOxford/cockpit#754] opened 2021-06-02 11:41 UTC
Using a Zyla camera, when you click on the Gain control button you see none as a single option. So far good cause these cameras have no gain, but when the button is released, cockpit freezes

**Comment by carandraug** [comment] 2021-06-03 20:21
I can reproduce this issue on Windows. On Linux it does not freeze.

**Comment by carandraug** [comment] 2021-06-03 20:37
This was also reproducible on the ximea cameras (who also do not have gain). Seemed to be caused because it was handling `EVT_LEFT_UP` instead of `EVT_BUTTON`. Fixed with 6c58d37 . Closing.

**Closed by carandraug** 2021-06-03 20:37 UTC
